export const attributeMapping: { [key: string]: string } = {
  is_hidden: 'Наличие у партнёров',
  type: 'Тип',
  sub_type: 'Тип вина',
  color: 'Цвет',
  country: 'Страна',
  sweetness: 'Сахар',
  year: 'Винтаж',
  region: 'Регион',
  volume: 'Объем',
  abv: 'Крепость',
  grapes: 'Сорт винограда',
  gastronomy: 'Гастрономия',
  min_price: 'Цена',
  rating_customer: 'Оценки пользователей',
  rating_expert: 'Оценки экспертов',
  acidity_level: 'Уровень кислотности',
  bodied_level: 'Тело',
  tannin_level: 'Уровень танинности',
  sweetness_level: 'Уровень сладости',
};
