import { IAttribute, IProductResponse } from '@/redux/services/types/admin';

export interface IMapEditProductToForm {
  productName: string,
  productId: number,
  briefInfo: string,
  name: string,
  producerId: number,
  description: string,
  image_url: string,
  temperature: number
}

export const mapEditProductToForm = (product: IProductResponse) => ({
  productName: product.base_product_card.name,
  productId: product.base_product_card.id,
  briefInfo: product.base_product_card.brief_info,
  name: product.base_product_card.producer.name,
  producerId: product.base_product_card.producer.id,
  description: product.base_product_card.producer.description,
  image_url: product.base_product_card.producer.image_url,
  temperature: product.base_product_card.temperature,
  images: product.images,
  prefix: product.prefix,
  suffix: product.suffix,
  year: product.year,
  dye: product.dye,
  taste: product.taste,
  flavour: product.flavour,
  degustation: product.degustation,
  style: product.style,
  price: product.price,
  is_hidden: product.is_hidden,
  region_place: product.region_place,
  world_place: product.world_place,
  vineyard_place: product.vineyard_place,
  vivino_rating: product.vivino_rating,
  rating_customer: product.rating_customer,
  rating_expert: product.rating_expert,
  synchronized_at: product.synchronized_at,
  country: product.country?.id,
  volume: product.volume?.id,
  materials: product.materials?.id,
  color: product.color?.id,
  region: product.region?.id,
  sub_type: product.sub_type?.id,
  type: product.type?.id,
  sweetness: product.sweetness?.id,
  additional_attributes: product?.additional_attributes?.map((attr) => ({
    attribute_id: attr.attribute_id,
    value: attr.value,
    attribute_title: attr.attribute_title,
  })),
  attributes: product?.attributes?.map((attr) => ({
    value_id: attr.value_id,
    attribute_id: attr.attribute_id,
    attribute_title: attr.attribute_title,
    value: attr.value,
  })),
  gastronomy: product?.gastronomy?.map((attr: IAttribute) => ({
    value_id: attr.value_id,
    value: attr.value,
    attribute_title: attr.attribute_title,
    attribute_id: attr.attribute_id,
  })),
  grapes: product?.grapes?.map((attr: IAttribute) => ({
    value_id: attr.value_id,
    value: attr.value,
    attribute_title: attr.attribute_title,
    attribute_id: attr.attribute_id,
  })),
  taste_notes: product?.taste_notes?.map((note) => ({
    id: note.id,
    name: note.name,
    percent: note.percent,
  })),
});
